name: CI/CD Pipeline Simulation

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Deploy to Dev
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RAILWAY_DEV_TOKEN }}" \
            https://railway.app/deploy

  deploy-to-test:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Test
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RAILWAY_TEST_TOKEN }}" \
            https://railway.app/deploy

  release:
    runs-on: ubuntu-latest
    needs: deploy-to-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Await Release Approval
        uses: hmarr/auto-approve-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Team
        run: echo "Release approved! Notify stakeholders."
