name: CI/CD Pipeline - Release

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Permite que o workflow seja disparado manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'  # Permite que o release seja acionado manualmente ou pelo push na branch main
    steps:
      - name: Await Release Approval (Manual Trigger)
        run: echo "Release approval is required before proceeding to PROD."

      - name: Notify Team
        run: echo "Release approved! Notify stakeholders."

      - name: Deploy to Production
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RAILWAY_PROD_TOKEN }}" \
            https://projeto-ci-cd-production.up.railway.app/
